"""
rag/repo_retriever.py

Repository-Aware Retriever — Phase 1

Upgrades the existing Retriever to search the full repo index,
not just PR files. When generate_token() changes, this finds:
  - auth.py       (imports generate_token)
  - jwt_service.py (depends on token format)
  - config.py     (defines TOKEN_EXPIRY used by generate_token)
  - middleware.py  (validates tokens generated by it)

This gives the LLM full context about HOW the changed code is
used across the codebase — not just what changed.

Design (senior AIML engineer perspective):
- Two-stage retrieval:
    Stage 1: semantic similarity (existing, works well)
    Stage 2: call-graph aware (new) — find callers/callees
             by matching function names in metadata
- Results are ranked by a combined score:
    0.6 * semantic_score + 0.4 * call_graph_score
- Self-file exclusion: skip chunks from the file being reviewed
  (you don't want the LLM to "review" unchanged code)
- Language filtering: only retrieve Python chunks for Python PRs
"""
from __future__ import annotations

import re
from dataclasses import dataclass

from embeddings.embed import Embedder
from vectordb.chroma_store import ChromaStore, RetrievedChunk
from ingestion.github_loader import PRFile
from config import cfg

# Collection name must match what RepoIndexer uses
REPO_COLLECTION = "repo_index"


@dataclass
class EnrichedChunk:
    """A retrieved chunk with extra context about why it was retrieved."""
    chunk_id:       str
    filename:       str
    language:       str
    section_name:   str
    section_type:   str
    content:        str
    start_line:     int
    end_line:       int
    score:          float
    retrieval_reason: str  # "semantic" | "caller" | "callee" | "shared_import"


class RepoAwareRetriever:
    """
    Two-stage retriever that searches the full repo index.

    Stage 1 — Semantic: embed the changed lines, find similar chunks.
    Stage 2 — Structural: find chunks that reference the same
              functions/classes as the changed file (callers/callees).

    Merges and deduplicates both result sets.
    """

    def __init__(self, embedder: Embedder = None):
        self.embedder   = embedder or Embedder()
        self._col       = None

    # ─────────────────────────────────────────────────────
    # PUBLIC API
    # ─────────────────────────────────────────────────────

    def retrieve_for_file(
        self,
        pr_file: PRFile,
        top_k: int = None,
    ) -> list[EnrichedChunk]:
        """
        Main entry point. Returns relevant chunks from across
        the entire repo for the given changed file.
        """
        top_k = top_k or cfg.top_k
        col   = self._get_collection()

        if col is None or col.count() == 0:
            print(
                f"[repo-retriever] Repo index empty — "
                f"run: python index_repo.py --repo owner/repo"
            )
            return []

        # Stage 1: semantic similarity
        semantic_chunks = self._semantic_search(pr_file, col, top_k * 2)

        # Stage 2: structural (caller/callee) search
        structural_chunks = self._structural_search(pr_file, col, top_k)

        # Merge and rank
        merged = self._merge_and_rank(semantic_chunks, structural_chunks, top_k)

        # Filter out the file being reviewed (avoid self-reference)
        merged = [
            c for c in merged
            if c.filename != pr_file.filename
        ]

        # Apply minimum score threshold
        merged = [
            c for c in merged
            if c.score >= cfg.min_similarity_score
        ]

        print(
            f"[repo-retriever] {pr_file.filename}: "
            f"{len(merged)} chunks "
            f"(semantic + structural, score≥{cfg.min_similarity_score})"
        )

        # Print what was found (useful for debugging)
        if merged:
            unique_files = list(dict.fromkeys(c.filename for c in merged))
            print(f"[repo-retriever] Related files found:")
            for f in unique_files[:6]:
                reason = next(
                    c.retrieval_reason for c in merged if c.filename == f
                )
                print(f"  → {f}  [{reason}]")

        return merged

    def retrieve_for_pr(
        self,
        files: list[PRFile],
        top_k_per_file: int = 5,
    ) -> dict[str, list[EnrichedChunk]]:
        """Retrieve related context for every file in a PR."""
        context_map:    dict[str, list[EnrichedChunk]] = {}
        seen_chunk_ids: set[str] = set()

        for pf in files:
            chunks = self.retrieve_for_file(pf, top_k=top_k_per_file)
            unique = []
            for c in chunks:
                if c.chunk_id not in seen_chunk_ids:
                    seen_chunk_ids.add(c.chunk_id)
                    unique.append(c)
            context_map[pf.filename] = unique

        return context_map

    # ─────────────────────────────────────────────────────
    # STAGE 1 — SEMANTIC SEARCH
    # ─────────────────────────────────────────────────────

    def _semantic_search(
        self,
        pr_file: PRFile,
        col,
        top_k: int,
    ) -> list[EnrichedChunk]:
        """Embed changed lines and find similar chunks."""
        query_text = self._build_query(pr_file)
        q_vec      = self.embedder.embed_query(query_text)

        language = getattr(pr_file, "language", "unknown")
        where    = (
            {"language": {"$eq": language}}
            if language and language != "unknown"
            else None
        )

        try:
            results = col.query(
                query_embeddings = [q_vec],
                n_results        = min(top_k, col.count()),
                where            = where,
                include          = ["documents", "metadatas", "distances"],
            )
        except Exception as e:
            print(f"[repo-retriever] Semantic search failed: {e}")
            return []

        chunks = []
        for i in range(len(results["ids"][0])):
            score = max(0.0, 1.0 - results["distances"][0][i])
            meta  = results["metadatas"][0][i]
            chunks.append(EnrichedChunk(
                chunk_id         = results["ids"][0][i],
                filename         = meta.get("filename", ""),
                language         = meta.get("language", ""),
                section_name     = meta.get("section_name", ""),
                section_type     = meta.get("section_type", ""),
                content          = results["documents"][0][i],
                start_line       = int(meta.get("start_line", 0)),
                end_line         = int(meta.get("end_line", 0)),
                score            = round(score, 3),
                retrieval_reason = "semantic",
            ))

        return chunks

    # ─────────────────────────────────────────────────────
    # STAGE 2 — STRUCTURAL SEARCH (callers/callees)
    # ─────────────────────────────────────────────────────

    def _structural_search(
        self,
        pr_file: PRFile,
        col,
        top_k: int,
    ) -> list[EnrichedChunk]:
        """
        Find chunks that reference functions defined in the changed file.

        If generate_token() is in the PR diff, this finds every chunk
        across the repo that CALLS generate_token() — giving the LLM
        full visibility into downstream impact.
        """
        changed_func_names = self._extract_changed_function_names(pr_file)
        changed_imports    = self._extract_imports_from_file(pr_file)

        if not changed_func_names and not changed_imports:
            return []

        chunks = []

        # Search for chunks that contain the changed function names
        for func_name in changed_func_names[:5]:  # top 5 to limit API calls
            try:
                # Text search: find chunks mentioning this function name
                results = col.query(
                    query_embeddings = [
                        self.embedder.embed_query(
                            f"function call {func_name} usage example"
                        )
                    ],
                    n_results        = min(top_k, col.count()),
                    include          = ["documents", "metadatas", "distances"],
                )

                for i in range(len(results["ids"][0])):
                    doc  = results["documents"][0][i]
                    meta = results["metadatas"][0][i]

                    # Only include if the chunk actually contains the function name
                    if func_name not in doc:
                        continue

                    score = max(0.0, 1.0 - results["distances"][0][i])

                    # Determine relationship: caller or shared dependency
                    reason = (
                        "caller"
                        if f"{func_name}(" in doc
                        else "references"
                    )

                    chunks.append(EnrichedChunk(
                        chunk_id         = results["ids"][0][i],
                        filename         = meta.get("filename", ""),
                        language         = meta.get("language", ""),
                        section_name     = meta.get("section_name", ""),
                        section_type     = meta.get("section_type", ""),
                        content          = doc,
                        start_line       = int(meta.get("start_line", 0)),
                        end_line         = int(meta.get("end_line", 0)),
                        score            = round(score * 0.85, 3),  # slight discount vs semantic
                        retrieval_reason = reason,
                    ))

            except Exception:
                continue

        return chunks

    # ─────────────────────────────────────────────────────
    # MERGE + RANK
    # ─────────────────────────────────────────────────────

    def _merge_and_rank(
        self,
        semantic:   list[EnrichedChunk],
        structural: list[EnrichedChunk],
        top_k:      int,
    ) -> list[EnrichedChunk]:
        """
        Merge semantic and structural results.
        If a chunk appears in both lists, boost its score.
        """
        seen:   dict[str, EnrichedChunk] = {}

        for chunk in semantic:
            seen[chunk.chunk_id] = chunk

        for chunk in structural:
            if chunk.chunk_id in seen:
                # Appeared in both — boost score
                existing = seen[chunk.chunk_id]
                existing.score = min(1.0, existing.score + 0.15)
                existing.retrieval_reason = (
                    f"{existing.retrieval_reason}+{chunk.retrieval_reason}"
                )
            else:
                seen[chunk.chunk_id] = chunk

        ranked = sorted(seen.values(), key=lambda c: c.score, reverse=True)
        return ranked[:top_k]

    # ─────────────────────────────────────────────────────
    # HELPERS
    # ─────────────────────────────────────────────────────

    def _build_query(self, pr_file: PRFile) -> str:
        """Build semantic query from changed lines only."""
        changed_lines = getattr(pr_file, "changed_lines", [])

        if not changed_lines:
            changed_lines = [
                line[1:]
                for line in getattr(pr_file, "patch", "").splitlines()
                if line.startswith("+") and not line.startswith("+++")
            ]

        if not changed_lines:
            changed_lines = pr_file.full_content.splitlines()[:30]

        return (
            f"Language: {pr_file.language}\n"
            f"File: {pr_file.filename}\n\n"
            f"Changed Code:\n"
            + "\n".join(changed_lines[:60])
        )

    def _extract_changed_function_names(self, pr_file: PRFile) -> list[str]:
        """Extract function/class names from the changed lines (diff)."""
        changed_lines = getattr(pr_file, "changed_lines", [])
        if not changed_lines:
            changed_lines = [
                line[1:]
                for line in getattr(pr_file, "patch", "").splitlines()
                if line.startswith("+") and not line.startswith("+++")
            ]

        combined = "\n".join(changed_lines)
        names = re.findall(
            r"(?:def|class|async def|function|const|let)\s+(\w+)",
            combined,
        )
        return list(dict.fromkeys(names))  # dedupe

    def _extract_imports_from_file(self, pr_file: PRFile) -> list[str]:
        """Extract what the changed file imports."""
        imports = re.findall(
            r"^(?:import|from)\s+(\S+)",
            pr_file.full_content,
            re.MULTILINE,
        )
        return list(dict.fromkeys(imports))

    def _get_collection(self):
        if self._col is not None:
            return self._col
        try:
            import chromadb
            client     = chromadb.PersistentClient(path=cfg.chroma_dir)
            self._col  = client.get_or_create_collection(
                name     = REPO_COLLECTION,
                metadata = {"hnsw:space": "cosine"},
            )
            return self._col
        except Exception as e:
            print(f"[repo-retriever] ChromaDB failed: {e}")
            return None