"""
agents/test_generator.py

Tier 2 — Feature 1: Auto Test Generation

For every changed function in the PR:
1. Extracts function signature + docstring + body
2. Generates pytest test cases covering:
   - Happy path
   - Edge cases (empty input, None, boundary values)
   - Security-specific tests (SQL injection strings, path traversal)
   - Error cases (exceptions expected)
3. Posts tests as a PR comment
4. Tracks estimated coverage delta

Why this matters in interviews:
  Shows you understand that code review isn't just finding bugs —
  it's ensuring the codebase stays testable and covered.
"""
from __future__ import annotations

import re
import ast
import json
from pathlib import Path
from dataclasses import dataclass

from config import cfg


@dataclass
class GeneratedTest:
    function_name: str
    filename:      str
    test_code:     str
    test_cases:    list[str]
    estimated_coverage_gain: float  # 0.0 - 1.0


class TestGeneratorAgent:

    def __init__(self):
        self._groq = None

    # ── Public API ────────────────────────────────────────

    def generate_for_pr(
        self,
        pr_files,
        pr_title: str = "",
    ) -> list[GeneratedTest]:
        """Generate tests for all changed functions across all PR files."""
        all_tests = []
        for pf in pr_files:
            if pf.language not in ("python", "javascript", "typescript"):
                continue
            tests = self.generate_for_file(pf)
            all_tests.extend(tests)
            print(f"[test-gen] {pf.filename}: {len(tests)} test suites generated")
        return all_tests

    def generate_for_file(self, pr_file) -> list[GeneratedTest]:
        """Extract changed functions and generate tests for each."""
        changed_funcs = self._extract_changed_functions(pr_file)
        if not changed_funcs:
            return []

        tests = []
        for func in changed_funcs[:5]:  # max 5 per file to save tokens
            result = self._generate_tests(func, pr_file)
            if result:
                tests.append(result)

        return tests

    def post_tests_to_pr(
        self,
        tests:     list[GeneratedTest],
        repo:      str,
        pr_number: int,
        loader,
    ) -> bool:
        """Post all generated tests as a single PR comment."""
        if not tests:
            return False

        import requests

        sections = []
        for t in tests:
            sections.append(
                f"### `{t.function_name}()` in `{t.filename}`\n\n"
                f"**Test cases covered:** {', '.join(t.test_cases)}\n\n"
                f"**Estimated coverage gain:** +{t.estimated_coverage_gain*100:.0f}%\n\n"
                f"```python\n{t.test_code}\n```"
            )

        body = (
            "## 🧪 Auto-Generated Test Cases\n\n"
            "The AI reviewed your changes and generated these test cases. "
            "Copy them into your test suite.\n\n"
            "---\n\n"
            + "\n\n---\n\n".join(sections)
            + "\n\n---\n*🤖 Generated by AI Code Review Test Generator*"
        )

        try:
            resp = requests.post(
                f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments",
                headers = loader.auth.headers(),
                json    = {"body": body},
                timeout = 20,
            )
            resp.raise_for_status()
            print(f"[test-gen] Posted {len(tests)} test suites to PR #{pr_number}")
            return True
        except Exception as e:
            print(f"[test-gen] Failed to post tests: {e}")
            return False

    # ── Function extraction ───────────────────────────────

    def _extract_changed_functions(self, pr_file) -> list[dict]:
        """Find functions that were actually changed in this PR."""
        patch        = getattr(pr_file, "patch", "")
        full_content = getattr(pr_file, "full_content", "")
        language     = getattr(pr_file, "language", "")

        if not full_content:
            return []

        # Get changed line numbers from diff
        changed_lines = self._parse_changed_lines(patch)
        if not changed_lines:
            return []

        if language == "python":
            return self._extract_python_functions(full_content, changed_lines, pr_file.filename)
        elif language in ("javascript", "typescript"):
            return self._extract_js_functions(full_content, changed_lines, pr_file.filename)

        return []

    def _extract_python_functions(
        self,
        content:       str,
        changed_lines: set[int],
        filename:      str,
    ) -> list[dict]:
        """Parse Python AST to find changed functions with their full context."""
        funcs = []
        try:
            tree = ast.parse(content)
            lines = content.splitlines()

            for node in ast.walk(tree):
                if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue

                func_lines = set(range(node.lineno, node.end_lineno + 1))
                if not func_lines & changed_lines:
                    continue

                # Extract function source
                func_src = "\n".join(lines[node.lineno-1 : node.end_lineno])

                # Get class context if method
                class_name = ""
                for parent in ast.walk(tree):
                    if isinstance(parent, ast.ClassDef):
                        for child in ast.walk(parent):
                            if child is node:
                                class_name = parent.name
                                break

                # Get docstring
                docstring = ast.get_docstring(node) or ""

                # Get args
                args = [a.arg for a in node.args.args]

                # Get return annotation
                returns = ""
                if node.returns:
                    returns = ast.unparse(node.returns)

                funcs.append({
                    "name":       node.name,
                    "class":      class_name,
                    "filename":   filename,
                    "source":     func_src,
                    "args":       args,
                    "returns":    returns,
                    "docstring":  docstring,
                    "start_line": node.lineno,
                    "end_line":   node.end_lineno,
                    "language":   "python",
                })

        except SyntaxError:
            pass

        return funcs

    def _extract_js_functions(
        self,
        content:       str,
        changed_lines: set[int],
        filename:      str,
    ) -> list[dict]:
        """Simple regex-based JS/TS function extraction."""
        funcs = []
        lines = content.splitlines()

        patterns = [
            r"(?:export\s+)?(?:async\s+)?function\s+(\w+)\s*\(",
            r"(?:export\s+)?(?:const|let)\s+(\w+)\s*=\s*(?:async\s+)?\(",
            r"(?:export\s+)?(?:const|let)\s+(\w+)\s*=\s*(?:async\s+)?function",
        ]

        for i, line in enumerate(lines):
            lineno = i + 1
            if lineno not in changed_lines:
                continue
            for pat in patterns:
                m = re.match(pat, line.strip())
                if m:
                    func_name = m.group(1)
                    end = min(i + 30, len(lines))
                    source = "\n".join(lines[i:end])
                    funcs.append({
                        "name":       func_name,
                        "class":      "",
                        "filename":   filename,
                        "source":     source[:800],
                        "args":       [],
                        "returns":    "",
                        "docstring":  "",
                        "start_line": lineno,
                        "end_line":   end,
                        "language":   "javascript",
                    })
                    break

        return funcs

    # ── Test generation via LLM ───────────────────────────

    def _generate_tests(self, func: dict, pr_file) -> GeneratedTest | None:
        language = func["language"]

        system = """You are a senior software engineer writing thorough test cases.
Generate complete, runnable test code.
Return ONLY valid JSON — no markdown, no explanation outside JSON.
{
  "test_code": "<complete test file content>",
  "test_cases": ["happy path", "edge case: None input", ...],
  "estimated_coverage_gain": 0.75
}"""

        class_prefix = f"{func['class']}." if func["class"] else ""
        full_name    = f"{class_prefix}{func['name']}"

        prompt = f"""Generate {language} tests for this function.

Function: {full_name}
File: {func['filename']}
Args: {func['args']}
Returns: {func['returns']}
Docstring: {func['docstring']}

Source code:
{func['source'][:1500]}

Requirements:
1. Use pytest (Python) or jest/vitest (JS/TS)
2. Cover: happy path, edge cases, error cases, security inputs
3. For security functions: test with injection strings ('; DROP TABLE--, ../../../etc/passwd)
4. Use descriptive test names: test_function_name_when_condition_then_result
5. Mock external dependencies (DB, HTTP, filesystem)
6. Each test must be standalone and runnable

Generate at least 4 test cases."""

        try:
            client = self._get_groq()
            resp   = client.chat.completions.create(
                model       = cfg.review_model,
                temperature = 0.1,
                max_tokens  = 2048,
                messages    = [
                    {"role": "system", "content": system},
                    {"role": "user",   "content": prompt},
                ],
            )
            text = resp.choices[0].message.content.strip()
            text = re.sub(r'```[a-z]*\n?', '', text).strip('`').strip()

            data = json.loads(text)

            return GeneratedTest(
                function_name            = func["name"],
                filename                 = func["filename"],
                test_code                = data.get("test_code", ""),
                test_cases               = data.get("test_cases", []),
                estimated_coverage_gain  = float(data.get("estimated_coverage_gain", 0.5)),
            )

        except Exception as e:
            print(f"[test-gen] Failed for {func['name']}: {e}")
            return None

    # ── Helpers ───────────────────────────────────────────

    def _parse_changed_lines(self, patch: str) -> set[int]:
        changed = set()
        line_num = 0
        for line in patch.splitlines():
            if line.startswith("@@"):
                m = re.search(r"\+(\d+)", line)
                if m:
                    line_num = int(m.group(1))
            elif line.startswith("+") and not line.startswith("+++"):
                changed.add(line_num)
                line_num += 1
            elif not line.startswith("-"):
                line_num += 1
        return changed

    def _get_groq(self):
        if self._groq is None:
            from groq import Groq
            self._groq = Groq(api_key=cfg.groq_api_key)
        return self._groq